### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by ericgaspar**
- Small permission fixes

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by nils-van-zuijlen** [comment]
The CI fails because of a too short password, is it possible to force it to use longer ones?

**Comment by nils-van-zuijlen** [comment]
!testme

**Comment by nils-van-zuijlen** [comment]
!testme

**Comment by nils-van-zuijlen** [comment]
@ericgaspar What do you think about my commits?

**Pull request merged**
