### PR TITLE
Fix linter

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by mrflos — APPROVED** [review]
ok merci, je ne savais pas que la convention etait avec des points.. 
On va tenter de passer YesWiki sur un format de versionning plus standard bientot

**Comment by mrflos** [comment]
j'attend le retour des tests du bot et je merge?

**Comment by ericgaspar** [comment]
Je pense que tu peux merger et faire un test sur la branche testing

**Pull request merged**
